#!/bin/sh

DIR=`pwd`
LIST_FILE='cscope.files'
DATABASE_FILE='cscope.out'

#check arguments

if [ $# -le 0 ];then
#find file in current dir
	  echo "${DIR}"
	  find $DIR \( -type f -o -type l \) > $$
else
#find file in dir which user give
	   > $$
	  for dir in $*;do
	  	find $dir \( -type f -o -type l \) >> $$
	  done
fi
rm -rf $LIST_FILE
rm -rf $DATABASE_FILE
#find the right file type what we want
cat $$ | egrep -i '\.([chly](xx|pp)*|cc|hh|java)$' | \
	   	 sed  -e 's/^\.\///' -e '/\.git/d' -e '/\.repo/d' -e '/\/svn\//d' -e '/\/CVS\//d' -e '/\/RCS\//d' -e '/\#/d'| \
		 sort > $LIST_FILE

rm -rf $$

cscope -b -i $LIST_FILE -f $DATABASE_FILE
		 
