#!/bin/bash
#H_S
# 依据dts文件生成对应dtb文件/打印dts文件包含文件树/展开dts所有包含文件为一个完整文件
#H_E
DTS_FILE=""
ALL_DTS="---all"
##################################################
#
# xd-dts -p xxx.dts -c xxx.dts
# -p : print all dts file tree
# -d : create dts file include all dsti 
# -b : create dtb file
################################################


# get command line options
while getopts "p:d:b:" dts_flg
do
    case $dts_flg in

        p) DTS_FILE="$OPTARG"	
			python ~/bin/dts-find.py $OPTARG

           ;;
		d) 	DTS_FILE="$OPTARG"
			ALL_DTS="$OPTARG"$ALL_DTS
			cpp -Wp,-MD,x.pre.tmp -nostdinc -I. -Iinclude  -undef -D__DTS__ -x assembler-with-cpp -o xx.dts.tmp $DTS_FILE
			dtc -I dts -O dts -o $ALL_DTS xx.dts.tmp
			rm -rf *tmp$
			rm -rf xx.dts.tmp
			;;
		b) 	DTS_FILE="$OPTARG"
			ALL_DTS=${OPTARG%.*}
			ALL_DTS=$ALL_DTS".dtb"
			cpp -Wp,-MD,x.pre.tmp -nostdinc -I. -Iinclude  -undef -D__DTS__ -x assembler-with-cpp -o xx.dts.tmp $DTS_FILE
			dtc -I dts -O dtb -o $ALL_DTS xx.dts.tmp
			rm -rf *tmp$
			rm -rf xx.dts.tmp
			;;
		
		?)
			;;
	esac
done





