#!/bin/bash
DTS_FILE=""
ALL_DTS="---all"
##################################################
#
# xd-dts -p xxx.dts -c xxx.dts
# -p : print all dts file tree
# -c : create all 
#
################################################


# get command line options
while getopts "p:c:" dts_flg
do
    case $dts_flg in

        p) DTS_FILE="$OPTARG"	
			python ~/bin/dts-find.py $OPTARG

           ;;
		c) 	DTS_FILE="$OPTARG"
			ALL_DTS="$OPTARG"$ALL_DTS
			dtc -I dts $DTS_FILE -O dts -o $ALL_DTS
			;;
		?)
			;;
	esac
done





