#!/bin/bash
#H_S
# 快速打开xd-cmd后查找的对应文件
#H_E

CMD_FILE="/tmp/xd-grep-tmp"

function use_info () {
	echo "===>use $0 v/e xxx<====="
}

function get_all_cmd(){
		 awk -F":" -v id=$1 '{ \
		 	 if($1 == id){ \
			  #str=sprintf("vim %s +%d",$2,$3); \
			  str=sprintf("emacsclient -c  %s &",$2); \
			  system(str)
		} \
	}' $CMD_FILE
}

if [ $# -le 0 ] ; then
 	use_info;
else
	get_all_cmd $1;
fi

