#!/bin/sh

file_name=$1

if [ $# -lt 1 ]; then
	echo "please input the files name which you want styled"
	exit 1
fi
echo $file_name
echo "`astyle --mode=c --style=linux --indent=spaces=4 --add-brackets  --indent-preprocessor --align-pointer=name --pad-oper --pad-header --unpad-paren --suffix=none --lineend=linux --indent-switches --indent-col1-comments --min-conditional-indent=1 --max-instatement-indent=80 ${file_name}`"
